
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 27.04.2009
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace sap
{

  [RfcStructure(AbapName ="BAPIRET2" , Length = 548, Length2 = 1088)]
  public class BAPIRET2 : SAPStructure
  {
    
    [RfcField(AbapName = "TYPE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 0, Offset2 = 0)]
    [XmlElement("TYPE")]
    public string Type
    { 
       get
       {
          return _Type;
       }
       set
       {
          _Type = value;
       }
    }
    private string _Type;

    [RfcField(AbapName = "ID", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Length2 = 40, Offset = 1, Offset2 = 2)]
    [XmlElement("ID")]
    public string Id
    { 
       get
       {
          return _Id;
       }
       set
       {
          _Id = value;
       }
    }
    private string _Id;

    [RfcField(AbapName = "NUMBER", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 3, Length2 = 6, Offset = 21, Offset2 = 42)]
    [XmlElement("NUMBER")]
    public string Number
    { 
       get
       {
          return _Number;
       }
       set
       {
          _Number = value;
       }
    }
    private string _Number;

    [RfcField(AbapName = "MESSAGE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 220, Length2 = 440, Offset = 24, Offset2 = 48)]
    [XmlElement("MESSAGE")]
    public string Message
    { 
       get
       {
          return _Message;
       }
       set
       {
          _Message = value;
       }
    }
    private string _Message;

    [RfcField(AbapName = "LOG_NO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Length2 = 40, Offset = 244, Offset2 = 488)]
    [XmlElement("LOG_NO")]
    public string Log_No
    { 
       get
       {
          return _Log_No;
       }
       set
       {
          _Log_No = value;
       }
    }
    private string _Log_No;

    [RfcField(AbapName = "LOG_MSG_NO", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 6, Length2 = 12, Offset = 264, Offset2 = 528)]
    [XmlElement("LOG_MSG_NO")]
    public string Log_Msg_No
    { 
       get
       {
          return _Log_Msg_No;
       }
       set
       {
          _Log_Msg_No = value;
       }
    }
    private string _Log_Msg_No;

    [RfcField(AbapName = "MESSAGE_V1", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 50, Length2 = 100, Offset = 270, Offset2 = 540)]
    [XmlElement("MESSAGE_V1")]
    public string Message_V1
    { 
       get
       {
          return _Message_V1;
       }
       set
       {
          _Message_V1 = value;
       }
    }
    private string _Message_V1;

    [RfcField(AbapName = "MESSAGE_V2", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 50, Length2 = 100, Offset = 320, Offset2 = 640)]
    [XmlElement("MESSAGE_V2")]
    public string Message_V2
    { 
       get
       {
          return _Message_V2;
       }
       set
       {
          _Message_V2 = value;
       }
    }
    private string _Message_V2;

    [RfcField(AbapName = "MESSAGE_V3", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 50, Length2 = 100, Offset = 370, Offset2 = 740)]
    [XmlElement("MESSAGE_V3")]
    public string Message_V3
    { 
       get
       {
          return _Message_V3;
       }
       set
       {
          _Message_V3 = value;
       }
    }
    private string _Message_V3;

    [RfcField(AbapName = "MESSAGE_V4", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 50, Length2 = 100, Offset = 420, Offset2 = 840)]
    [XmlElement("MESSAGE_V4")]
    public string Message_V4
    { 
       get
       {
          return _Message_V4;
       }
       set
       {
          _Message_V4 = value;
       }
    }
    private string _Message_V4;

    [RfcField(AbapName = "PARAMETER", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 32, Length2 = 64, Offset = 470, Offset2 = 940)]
    [XmlElement("PARAMETER")]
    public string Parameter
    { 
       get
       {
          return _Parameter;
       }
       set
       {
          _Parameter = value;
       }
    }
    private string _Parameter;

    [RfcField(AbapName = "ROW", RfcType = RFCTYPE.RFCTYPE_INT, Length = 4, Length2 = 4, Offset = 504, Offset2 = 1004)]
    [XmlElement("ROW")]
    public int Row
    { 
       get
       {
          return _Row;
       }
       set
       {
          _Row = value;
       }
    }
    private int _Row;

    [RfcField(AbapName = "FIELD", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 30, Length2 = 60, Offset = 508, Offset2 = 1008)]
    [XmlElement("FIELD")]
    public string Field
    { 
       get
       {
          return _Field;
       }
       set
       {
          _Field = value;
       }
    }
    private string _Field;

    [RfcField(AbapName = "SYSTEM", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 538, Offset2 = 1068)]
    [XmlElement("SYSTEM")]
    public string System
    { 
       get
       {
          return _System;
       }
       set
       {
          _System = value;
       }
    }
    private string _System;

  }

}
