
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 27.04.2009
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace sap
{

  // Client SAP proxy class
  [WebServiceBinding(Name="", Namespace="urn:sap-com:document:sap:rfc:functions")]
  public class SAPProxy : SAPClient
  {
    // Constructors
    public SAPProxy(){}
    public SAPProxy(string ConnectionString) : base(ConnectionString){}

  
    // Exception constants 
    // Client call Methods
    

    // Generated method used to call the remote function module ZITC_RFC_GET_DATA_FROM_PORTAL    
    // Throws:  
    [RfcMethod(AbapName = "ZITC_RFC_GET_DATA_FROM_PORTAL")]
    [SoapDocumentMethodAttribute("http://tempuri.org/ZITC_RFC_GET_DATA_FROM_PORTAL",
     RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
     RequestElementName = "ZITC_RFC_GET_DATA_FROM_PORTAL",
     ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
     ResponseElementName = "ZITC_RFC_GET_DATA_FROM_PORTAL.Response")]
    public void Zitc_Rfc_Get_Data_From_Portal (

     [RfcParameter(AbapName = "IM_BEGDA",RfcType=RFCTYPE.RFCTYPE_DATE, Optional = true, Direction = RFCINOUT.IN, Length = 8, Length2 = 16)]
     [XmlElement("IM_BEGDA", IsNullable=false)]
     string Im_Begda,
     [RfcParameter(AbapName = "IM_ENDDA",RfcType=RFCTYPE.RFCTYPE_DATE, Optional = true, Direction = RFCINOUT.IN, Length = 8, Length2 = 16)]
     [XmlElement("IM_ENDDA", IsNullable=false)]
     string Im_Endda,
     [RfcParameter(AbapName = "IM_FEATURE",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.IN, Length = 1, Length2 = 2)]
     [XmlElement("IM_FEATURE", IsNullable=false)]
     string Im_Feature,
     [RfcParameter(AbapName = "IM_PERNR",RfcType=RFCTYPE.RFCTYPE_NUM, Optional = true, Direction = RFCINOUT.IN, Length = 8, Length2 = 16)]
     [XmlElement("IM_PERNR", IsNullable=false)]
     string Im_Pernr,
     [RfcParameter(AbapName = "EX_ERROR_MESSAGE",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = true, Direction = RFCINOUT.INOUT)]
     [XmlArray("EX_ERROR_MESSAGE", IsNullable=false)]
     [XmlArrayItem("item", IsNullable=false)]
     ref BAPIRET2Table Ex_Error_Message,
     [RfcParameter(AbapName = "EX_HR_POLIST_RFC_STR",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = true, Direction = RFCINOUT.INOUT)]
     [XmlArray("EX_HR_POLIST_RFC_STR", IsNullable=false)]
     [XmlArrayItem("item", IsNullable=false)]
     ref ZHR_POLIST_RFC_STRTable Ex_Hr_Polist_Rfc_Str)
    {
        object[]results = null;
        results = this.SAPInvoke("Zitc_Rfc_Get_Data_From_Portal",new object[] {
                            Im_Begda,Im_Endda,Im_Feature,Im_Pernr,Ex_Error_Message,Ex_Hr_Polist_Rfc_Str});
        Ex_Error_Message = (BAPIRET2Table) results[0];
        Ex_Hr_Polist_Rfc_Str = (ZHR_POLIST_RFC_STRTable) results[1];

        return;
    }


    // Generated method used to call the remote function module ZITC_RFC_GET_PERNR    
    // Throws:  
    [RfcMethod(AbapName = "ZITC_RFC_GET_PERNR")]
    [SoapDocumentMethodAttribute("http://tempuri.org/ZITC_RFC_GET_PERNR",
     RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
     RequestElementName = "ZITC_RFC_GET_PERNR",
     ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
     ResponseElementName = "ZITC_RFC_GET_PERNR.Response")]
    public void Zitc_Rfc_Get_Pernr (

     [RfcParameter(AbapName = "IM_SYSID",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.IN, Length = 30, Length2 = 60)]
     [XmlElement("IM_SYSID", IsNullable=false)]
     string Im_Sysid,
     [RfcParameter(AbapName = "IM_ZZLOGIN",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.IN, Length = 20, Length2 = 40)]
     [XmlElement("IM_ZZLOGIN", IsNullable=false)]
     string Im_Zzlogin,
     [RfcParameter(AbapName = "IM_ZZPASSW",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.IN, Length = 12, Length2 = 24)]
     [XmlElement("IM_ZZPASSW", IsNullable=false)]
     string Im_Zzpassw,
     [RfcParameter(AbapName = "EX_PERNR",RfcType=RFCTYPE.RFCTYPE_NUM, Optional = true, Direction = RFCINOUT.OUT, Length = 8, Length2 = 16)]
     [XmlElement("EX_PERNR", IsNullable=false)]
     out string Ex_Pernr,
     [RfcParameter(AbapName = "EX_ERROR_MESSAGE",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = true, Direction = RFCINOUT.INOUT)]
     [XmlArray("EX_ERROR_MESSAGE", IsNullable=false)]
     [XmlArrayItem("item", IsNullable=false)]
     ref BAPIRET2Table Ex_Error_Message)
    {
        object[]results = null;
        results = this.SAPInvoke("Zitc_Rfc_Get_Pernr",new object[] {
                            Im_Sysid,Im_Zzlogin,Im_Zzpassw,Ex_Error_Message});
        Ex_Pernr = (string) results[0];
        Ex_Error_Message = (BAPIRET2Table) results[1];

        return;
    }


    // Generated method used to call the remote function module ZITC_RFC_DATA_TRANS_FROM_HRP    
    // Throws:  
    [RfcMethod(AbapName = "ZITC_RFC_DATA_TRANS_FROM_HRP")]
    [SoapDocumentMethodAttribute("http://tempuri.org/ZITC_RFC_DATA_TRANS_FROM_HRP",
     RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
     RequestElementName = "ZITC_RFC_DATA_TRANS_FROM_HRP",
     ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
     ResponseElementName = "ZITC_RFC_DATA_TRANS_FROM_HRP.Response")]
    public void Zitc_Rfc_Data_Trans_From_Hrp (

     [RfcParameter(AbapName = "IM_TB_OVERHOURS_DIV",RfcType=RFCTYPE.RFCTYPE_XMLDATA, Optional = false, Direction = RFCINOUT.IN)]
     [XmlArray("IM_TB_OVERHOURS_DIV", IsNullable=false)]
     [XmlArrayItem("item", IsNullable=false)]
     ZTB_OVERHOURS_DIV_TYPE_TAB Im_Tb_Overhours_Div,
     [RfcParameter(AbapName = "IM_TB_OVERHOURS_MAN",RfcType=RFCTYPE.RFCTYPE_XMLDATA, Optional = false, Direction = RFCINOUT.IN)]
     [XmlArray("IM_TB_OVERHOURS_MAN", IsNullable=false)]
     [XmlArrayItem("item", IsNullable=false)]
     ZTB_OVERHOURS_MAN_TYPE_TAB Im_Tb_Overhours_Man,
     [RfcParameter(AbapName = "IM_TB_OVERHOURS_T13",RfcType=RFCTYPE.RFCTYPE_XMLDATA, Optional = false, Direction = RFCINOUT.IN)]
     [XmlArray("IM_TB_OVERHOURS_T13", IsNullable=false)]
     [XmlArrayItem("item", IsNullable=false)]
     ZTB_OVERHOURS_T13_TYPE_TAB Im_Tb_Overhours_T13,
     [RfcParameter(AbapName = "EX_ERROR_MESSAGE",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("EX_ERROR_MESSAGE", IsNullable=false)]
     [XmlArrayItem("item", IsNullable=false)]
     ref BAPIRET2Table Ex_Error_Message)
    {
        object[]results = null;
        results = this.SAPInvoke("Zitc_Rfc_Data_Trans_From_Hrp",new object[] {
                            Im_Tb_Overhours_Div,Im_Tb_Overhours_Man,Im_Tb_Overhours_T13,Ex_Error_Message});
        Ex_Error_Message = (BAPIRET2Table) results[0];

        return;
    }


    // Generated method used to call the remote function module ZITC_RFC_GET_FEATURE    
    // Throws:  
    [RfcMethod(AbapName = "ZITC_RFC_GET_FEATURE")]
    [SoapDocumentMethodAttribute("http://tempuri.org/ZITC_RFC_GET_FEATURE",
     RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
     RequestElementName = "ZITC_RFC_GET_FEATURE",
     ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
     ResponseElementName = "ZITC_RFC_GET_FEATURE.Response")]
    public void Zitc_Rfc_Get_Feature (

     [RfcParameter(AbapName = "IM_PERNR",RfcType=RFCTYPE.RFCTYPE_NUM, Optional = true, Direction = RFCINOUT.IN, Length = 8, Length2 = 16)]
     [XmlElement("IM_PERNR", IsNullable=false)]
     string Im_Pernr,
     [RfcParameter(AbapName = "EX_ERROR_MESSAGE",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = true, Direction = RFCINOUT.INOUT)]
     [XmlArray("EX_ERROR_MESSAGE", IsNullable=false)]
     [XmlArrayItem("item", IsNullable=false)]
     ref BAPIRET2Table Ex_Error_Message,
     [RfcParameter(AbapName = "EX_FEATURE",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = true, Direction = RFCINOUT.INOUT)]
     [XmlArray("EX_FEATURE", IsNullable=false)]
     [XmlArrayItem("item", IsNullable=false)]
     ref ZFEATURE_STRTable Ex_Feature)
    {
        object[]results = null;
        results = this.SAPInvoke("Zitc_Rfc_Get_Feature",new object[] {
                            Im_Pernr,Ex_Error_Message,Ex_Feature});
        Ex_Error_Message = (BAPIRET2Table) results[0];
        Ex_Feature = (ZFEATURE_STRTable) results[1];

        return;
    }


  } // rfm client proxy


} // Namespace
