
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 27.04.2009
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace sap
{

  [RfcStructure(AbapName ="ZFEATURE_STR" , Length = 41, Length2 = 82)]
  public class ZFEATURE_STR : SAPStructure
  {
    
    [RfcField(AbapName = "FEATURE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 0, Offset2 = 0)]
    [XmlElement("FEATURE")]
    public string Feature
    { 
       get
       {
          return _Feature;
       }
       set
       {
          _Feature = value;
       }
    }
    private string _Feature;

    [RfcField(AbapName = "FEATURE_TEXT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Length2 = 80, Offset = 1, Offset2 = 2)]
    [XmlElement("FEATURE_TEXT")]
    public string Feature_Text
    { 
       get
       {
          return _Feature_Text;
       }
       set
       {
          _Feature_Text = value;
       }
    }
    private string _Feature_Text;

  }

}
