
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 27.04.2009
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace sap
{

  public class ZFEATURE_STRTable : SAPTable 
  {
    public static Type GetElementType() 
    {
        return (typeof(ZFEATURE_STR));
    }
 
    public override object CreateNewRow()
    { 
        return new ZFEATURE_STR();
    }
     
    public ZFEATURE_STR this[int index] 
    {
        get 
        {
            return ((ZFEATURE_STR)(List[index]));
        }
        set 
        {
            List[index] = value;
        }
    }
        
    public int Add(ZFEATURE_STR value) 
    {
        return List.Add(value);
    }
        
    public void Insert(int index, ZFEATURE_STR value) 
    {
        List.Insert(index, value);
    }
        
    public int IndexOf(ZFEATURE_STR value) 
    {
        return List.IndexOf(value);
    }
        
    public bool Contains(ZFEATURE_STR value) 
    {
        return List.Contains(value);
    }
        
    public void Remove(ZFEATURE_STR value) 
    {
        List.Remove(value);
    }
        
    public void CopyTo(ZFEATURE_STR[] array, int index) 
    {
        List.CopyTo(array, index);
	}
  }
}
