
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 27.04.2009
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace sap
{

  public class ZHR_POLIST_RFC_STRTable : SAPTable 
  {
    public static Type GetElementType() 
    {
        return (typeof(ZHR_POLIST_RFC_STR));
    }
 
    public override object CreateNewRow()
    { 
        return new ZHR_POLIST_RFC_STR();
    }
     
    public ZHR_POLIST_RFC_STR this[int index] 
    {
        get 
        {
            return ((ZHR_POLIST_RFC_STR)(List[index]));
        }
        set 
        {
            List[index] = value;
        }
    }
        
    public int Add(ZHR_POLIST_RFC_STR value) 
    {
        return List.Add(value);
    }
        
    public void Insert(int index, ZHR_POLIST_RFC_STR value) 
    {
        List.Insert(index, value);
    }
        
    public int IndexOf(ZHR_POLIST_RFC_STR value) 
    {
        return List.IndexOf(value);
    }
        
    public bool Contains(ZHR_POLIST_RFC_STR value) 
    {
        return List.Contains(value);
    }
        
    public void Remove(ZHR_POLIST_RFC_STR value) 
    {
        List.Remove(value);
    }
        
    public void CopyTo(ZHR_POLIST_RFC_STR[] array, int index) 
    {
        List.CopyTo(array, index);
	}
  }
}
